version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "4000:4000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # Keep only HTTP for now, remove 443 if not using SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Ensure this NGINX config is set for HTTP only
    depends_on:
      - frontend
      - backend
