version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "4000:4000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/bluepiemeta.com/fullchain.pem:/etc/letsencrypt/live/bluepiemeta.com/fullchain.pem
      - /etc/letsencrypt/live/bluepiemeta.com/privkey.pem:/etc/letsencrypt/live/bluepiemeta.com/privkey.pem
